<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260304121334 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_image DROP CONSTRAINT fk_d32ed04059d8a214');
        $this->addSql('DROP TABLE recipe_image');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, "position" INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d32ed04059d8a214 ON recipe_image (recipe_id)');
        $this->addSql('ALTER TABLE recipe_image ADD CONSTRAINT fk_d32ed04059d8a214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
